exemples = {
    "leaf": {
        "format": "png",
        "axiom": "a",
        "backColor": "#000000",
        "angle": 45,
        "rules": ["F -> >F<", "a -> F[+x]Fb", "b -> F[-y]Fa", "x -> a", "y -> b"],
        "depth": 5,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36,
        "lineLength":1
    },
    "Bushes": {
        "format": "png",
        "axiom": "Y",
        "backColor": "#000000",
        "angle": 25.7,
        "rules": ["X -> X[-FFF][+FFF]FX", "Y -> YFX[+Y][-Y]"],
        "depth": 1,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Bushes2": {
        "format": "png",
        "axiom": "F",
        "backColor": "#000000",
        "angle": 22.5,
        "rules": ["F -> FF+[+F-F-F]-[-F+F+F]"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Bushes3": {
        "format": "png",
        "axiom": "F",
        "backColor": "#000000",
        "angle": 35,
        "rules": ["F -> F[+FF][-FF]F[-F][+F]F"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Saupe": {
        "format": "png",
        "axiom": "VZFFF",
        "backColor": "#000000",
        "angle": 20,
        "rules": ["V -> [+++W][---W]YV", "W -> +X[-W]Z", "X -> -W[+X]Z", "Y -> YZ", "Z -> [-FFF][+FFF]F"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Saupe2": {
        "format": "png",
        "axiom": "FX",
        "backColor": "#000000",
        "angle": 40,
        "rules": ["X -> >[-FX]+FX"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "sticks": {
        "format": "png",
        "axiom": "X",
        "backColor": "#000000",
        "angle": 20,
        "rules": ["F -> FF\n", "X -> F[+X]F[-X]+X"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "algae": {
        "format": "png",
        "axiom": "aF",
        "backColor": "#000000",
        "angle": 12,
        "rules": ["a -> FFFFFv[+++h][---q]fb",
            "b -> FFFFFv[+++h][---q]fc",
            "c -> FFFFFv[+++fa]fd",
            "d -> FFFFFv[+++h][---q]fe",
            "e -> FFFFFv[+++h][---q]fg",
            "g -> FFFFFv[---fa]fa",
            "h -> ifFF",
            "i -> fFFF[--m]j",
            "j -> fFFF[--n]k",
            "k -> fFFF[--o]l",
            "l -> fFFF[--p]",
            "m -> fFn",
            "n -> fFo",
            "o -> fFp",
            "p -> fF",
            "q -> rfF",
            "r -> fFFF[++m]s",
            "s -> fFFF[++n]t",
            "t -> fFFF[++o]u",
            "u -> fFFF[++p]",
            "0v -> Fv"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Weed": {
        "format": "png",
        "axiom": "F",
        "backColor": "#000000",
        "angle": 22.5,
        "rules": ["F -> FF-[XY]+[XY]", "X -> +FY", "Y -> -FX"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    }, "Triangle": {
        "format": "png",
        "axiom": "F+F+F",
        "backColor": "#000000",
        "angle": 120,
        "rules": ["F -> F-F+F"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Quadratic Gosper": {
        "format": "png",
        "axiom": "-YF",
        "backColor": "#000000",
        "angle": 90,
        "rules": ["X -> XFX-YF-YF+FX+FX-YF-YFFX+YF+FXFXYF-FX+YF+FXFX+YF-FXYF-YF-FX+FX+YFYF-",
            "Y -> +FXFX-YF-YF+FX+FXYF+FX-YFYF-FX-YF+FXYFYF-FX-YFFX+FX+YF-YF-FX+FX+YFY"],
        "depth": 3,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    },
    "Square Sierpinski": {
        "format": "png",
        "axiom": "F+XF+F+XF",
        "backColor": "#000000",
        "angle": 90,
        "rules": ["X -> XF-F+F-XF+F+XF-F+F-X"],
        "depth": 10,
        "lineColor": "#7CFC00",
        "lineWidth": 1,
        "lengthFactor": 1.36
    }
};